index:
    path: /
    defaults: { _controller: index_controller:indexAction }
    methods: [GET]

options:
    path: /query
    defaults: { _controller: index_controller:optionsAction }
    methods: [OPTIONS]

query:
    path: /query
    defaults: { _controller: index_controller:queryAction }
    methods: [POST]
