get_index:
    path: /
    defaults: { _controller: index_controller:indexAction }
    methods: [GET]

options_search:
    path: /search
    defaults: { _controller: index_controller:optionsAction }
    methods: [OPTIONS]

options_query:
    path: /query
    defaults: { _controller: index_controller:optionsAction }
    methods: [OPTIONS]

post_query:
    path: /query
    defaults: { _controller: index_controller:queryAction }
    methods: [POST]
