get_index:
    path: /{database}/
    defaults: { _controller: index_controller:indexAction }
    methods: [GET]

options_search:
    path: /{database}/search
    defaults: { _controller: index_controller:optionsAction }
    methods: [OPTIONS]

post_search:
    path: /{database}/search
    defaults: { _controller: index_controller:searchAction }
    methods: [POST]

options_query:
    path: /query
    defaults: { _controller: index_controller:optionsAction }
    methods: [OPTIONS]

post_query:
    path: /query
    defaults: { _controller: index_controller:queryAction }
    methods: [POST]
