services:
    index_controller:
        class: AppBundle\Controller\IndexController
        arguments: ['%database_host%', '%database_port%', '%time_fields%', '@pomm']
    cors:
        class: AppBundle\EventListener\CorsResponseListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
