services:
    index_controller:
        class: AppBundle\Controller\IndexController
        arguments: ['%database_host%', '%database_port%']
    cors:
        class: AppBundle\EventListener\CorsResponseListener
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
